// Code generated by crdtsync-codegen from schema "note" v1. DO NOT EDIT.
// Typed accessors over crdtsync's path surface; regenerate on schema change.
package notegen

import "github.com/faiscadev/crdtsync/sdks/go/crdtsync"

// Note holds typed accessors for schema type "Note".
type Note struct {
	doc  *crdtsync.Document
	path [][]byte
}

// slot "title": text "Title"
func (x *Note) GetTitle() (string, bool) {
	return x.doc.TextGet(joinPath(x.path, []byte("title")))
}
func (x *Note) LenTitle() (uint, bool) {
	return x.doc.TextLen(joinPath(x.path, []byte("title")))
}
func (x *Note) InsertTitle(index uint, text string) []byte {
	return x.doc.TextInsert(joinPath(x.path, []byte("title")), index, text)
}
func (x *Note) DeleteTitle(index, count uint) []byte {
	return x.doc.TextDelete(joinPath(x.path, []byte("title")), index, count)
}

// slot "views": counter "Views"
func (x *Note) GetViews() (int64, bool) {
	return x.doc.GetCounter(joinPath(x.path, []byte("views")))
}
func (x *Note) IncViews(amount uint32) []byte {
	return x.doc.Inc(joinPath(x.path, []byte("views")), amount)
}
func (x *Note) DecViews(amount uint32) []byte {
	return x.doc.Dec(joinPath(x.path, []byte("views")), amount)
}

// slot "tags": list "Tags"
func (x *Note) LenTags() (uint, bool) {
	return x.doc.ListLen(joinPath(x.path, []byte("tags")))
}
func (x *Note) GetTags(index uint) ([]byte, bool) {
	return x.doc.ListGet(joinPath(x.path, []byte("tags")), index)
}
func (x *Note) InsertTags(index uint, value []byte) []byte {
	return x.doc.ListInsert(joinPath(x.path, []byte("tags")), index, value)
}
func (x *Note) DeleteTags(index uint) []byte {
	return x.doc.ListDelete(joinPath(x.path, []byte("tags")), index)
}

// slot "meta": map "Meta"
func (x *Note) Meta() *Meta {
	return &Meta{doc: x.doc, path: joinPath(x.path, []byte("meta"))}
}

// Meta holds typed accessors for schema type "Meta".
type Meta struct {
	doc  *crdtsync.Document
	path [][]byte
}

// slot "priority": register "Priority"
func (x *Meta) GetPriority() (int64, bool) {
	return x.doc.GetInt(joinPath(x.path, []byte("priority")))
}
func (x *Meta) SetPriority(value int64) []byte {
	return x.doc.RegisterInt(joinPath(x.path, []byte("priority")), value)
}

// Bind wraps a crdtsync.Document at the schema root.
func Bind(doc *crdtsync.Document) *Note {
	return &Note{doc: doc}
}

// joinPath returns prefix with key appended, copying so sibling accessors
// never share a backing array.
func joinPath(prefix [][]byte, key []byte) [][]byte {
	out := make([][]byte, len(prefix)+1)
	copy(out, prefix)
	out[len(prefix)] = key
	return out
}
