# Generated by crdtsync-codegen from schema "collide" v1. Do not edit.
# Typed accessors over crdtsync's path surface; regenerate on schema change.
from typing import List, Optional

class C:
    """Typed accessors for schema type "C"."""

    def __init__(self, doc, path: Optional[List[bytes]] = None) -> None:
        self._doc = doc
        self._path = list(path) if path else []

    # slot "a-b": counter "Ctr"
    def get_a_b(self) -> Optional[int]:
        return self._doc.get_counter(self._path + [b"a-b"])
    def inc_a_b(self, amount: int) -> bytes:
        return self._doc.inc(self._path + [b"a-b"], amount)
    def dec_a_b(self, amount: int) -> bytes:
        return self._doc.dec(self._path + [b"a-b"], amount)

    # slot "a_b": counter "Ctr"
    def get_a_b_2(self) -> Optional[int]:
        return self._doc.get_counter(self._path + [b"a_b"])
    def inc_a_b_2(self, amount: int) -> bytes:
        return self._doc.inc(self._path + [b"a_b"], amount)
    def dec_a_b_2(self, amount: int) -> bytes:
        return self._doc.dec(self._path + [b"a_b"], amount)

    # slot "a b": counter "Ctr"
    def get_a_b_3(self) -> Optional[int]:
        return self._doc.get_counter(self._path + [b"a b"])
    def inc_a_b_3(self, amount: int) -> bytes:
        return self._doc.inc(self._path + [b"a b"], amount)
    def dec_a_b_3(self, amount: int) -> bytes:
        return self._doc.dec(self._path + [b"a b"], amount)


def bind(doc) -> "C":
    """Wrap a crdtsync.Document at the schema root."""
    return C(doc)
