# Generated by crdtsync-codegen from schema "note" v1. Do not edit.
# Typed accessors over crdtsync's path surface; regenerate on schema change.
from typing import List, Optional

class Note:
    """Typed accessors for schema type "Note"."""

    def __init__(self, doc, path: Optional[List[bytes]] = None) -> None:
        self._doc = doc
        self._path = list(path) if path else []

    # slot "title": text "Title"
    def get_title(self) -> Optional[str]:
        return self._doc.text_get(self._path + [b"title"])
    def len_title(self) -> Optional[int]:
        return self._doc.text_len(self._path + [b"title"])
    def insert_title(self, index: int, text: str) -> bytes:
        return self._doc.text_insert(self._path + [b"title"], index, text)
    def delete_title(self, index: int, count: int) -> bytes:
        return self._doc.text_delete(self._path + [b"title"], index, count)

    # slot "views": counter "Views"
    def get_views(self) -> Optional[int]:
        return self._doc.get_counter(self._path + [b"views"])
    def inc_views(self, amount: int) -> bytes:
        return self._doc.inc(self._path + [b"views"], amount)
    def dec_views(self, amount: int) -> bytes:
        return self._doc.dec(self._path + [b"views"], amount)

    # slot "tags": list "Tags"
    def len_tags(self) -> Optional[int]:
        return self._doc.list_len(self._path + [b"tags"])
    def get_tags(self, index: int) -> Optional[bytes]:
        return self._doc.list_get(self._path + [b"tags"], index)
    def insert_tags(self, index: int, value: bytes) -> bytes:
        return self._doc.list_insert(self._path + [b"tags"], index, value)
    def delete_tags(self, index: int) -> bytes:
        return self._doc.list_delete(self._path + [b"tags"], index)

    # slot "meta": map "Meta"
    def meta(self) -> "Meta":
        return Meta(self._doc, self._path + [b"meta"])

class Meta:
    """Typed accessors for schema type "Meta"."""

    def __init__(self, doc, path: Optional[List[bytes]] = None) -> None:
        self._doc = doc
        self._path = list(path) if path else []

    # slot "priority": register "Priority"
    def get_priority(self) -> Optional[int]:
        return self._doc.get_int(self._path + [b"priority"])
    def set_priority(self, value: int) -> bytes:
        return self._doc.register_int(self._path + [b"priority"], value)


def bind(doc) -> "Note":
    """Wrap a crdtsync.Document at the schema root."""
    return Note(doc)
