//! Typed-SDK codegen: read a registered [`Schema`] and emit typed accessor
//! wrappers for a target SDK language.
//!
//! The generated code is a thin, type-annotated facade over the raw path-string
//! surface an SDK already exposes: for each declared map slot it emits an
//! accessor that forwards to the existing document methods with the slot's path
//! and type baked in, so a consumer gets `note.get_title()` instead of
//! `doc.text_get([b"title"])`. Codegen only *reads* the schema — it never alters
//! the [`Schema`] type or the wire format.
//!
//! Output is deterministic: types and slots are emitted in the schema's own
//! declaration order, and the header carries no timestamp, so regenerating an
//! unchanged schema is a no-op diff.
//!
//! Python is the first target ([`generate_python`]); the emitter is structured
//! per-language so Go / TypeScript can follow the same shape.

use crdtsync_core::schema::{Schema, TypeDef};

/// Emit a Python module of typed accessors for `schema`.
///
/// One class is emitted per declared map type (named after the type). Each class
/// wraps a `crdtsync.Document` plus the path prefix it lives at, and exposes a
/// typed accessor per slot that forwards to the document's path surface:
///
/// - a `register` slot → `get_<slot>() -> Optional[int]` / `set_<slot>(value)`,
/// - a `counter` slot → `get_<slot>()` / `inc_<slot>(amount)` / `dec_<slot>(amount)`,
/// - a `text` slot → `get_<slot>() -> Optional[str]` / `insert_<slot>` / `delete_<slot>` / `len_<slot>`,
/// - a `list` slot → `len_<slot>` / `get_<slot>(index)` / `insert_<slot>(index, value)` / `delete_<slot>(index)`,
/// - a `map` slot → `<slot>() -> <NestedType>`, a wrapper rooted at the nested path.
///
/// An `xml` slot (or one whose type is undeclared) is emitted as a comment: those
/// surfaces are a follow-on. A `register` is treated as an integer scalar — its
/// declared bounds are numeric; a bytes-valued register uses the raw path.
pub fn generate_python(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Generated by crdtsync-codegen from schema {:?} v{}. Do not edit.\n",
        schema.name(),
        schema.version(),
    ));
    out.push_str("# Typed accessors over crdtsync's path surface; regenerate on schema change.\n");
    out.push_str("from typing import List, Optional\n\n");

    for (type_name, def) in schema.types() {
        if let TypeDef::Map { children } = def {
            emit_python_class(&mut out, schema, type_name, children);
        }
    }

    out.push_str(&format!(
        "\ndef bind(doc) -> {:?}:\n",
        py_class_name(schema.root())
    ));
    out.push_str("    \"\"\"Wrap a crdtsync.Document at the schema root.\"\"\"\n");
    out.push_str(&format!(
        "    return {}(doc)\n",
        py_class_name(schema.root())
    ));
    out
}

/// Emit one Python wrapper class for a map type and its slots.
fn emit_python_class(
    out: &mut String,
    schema: &Schema,
    type_name: &str,
    children: &[(String, String)],
) {
    let class = py_class_name(type_name);
    out.push_str(&format!("class {class}:\n"));
    out.push_str(&format!(
        "    \"\"\"Typed accessors for schema type {type_name:?}.\"\"\"\n\n"
    ));
    out.push_str("    def __init__(self, doc, path: Optional[List[bytes]] = None) -> None:\n");
    out.push_str("        self._doc = doc\n");
    out.push_str("        self._path = list(path) if path else []\n");

    for (slot, slot_type) in children {
        out.push('\n');
        let key = py_bytes_literal(slot);
        let ident = py_ident(slot);
        match schema.type_def(slot_type) {
            Some(TypeDef::Register { .. }) => {
                emit_line(out, &format!("# slot {slot:?}: register {slot_type:?}"));
                emit_getter(
                    out,
                    &format!("get_{ident}"),
                    "Optional[int]",
                    "get_int",
                    &key,
                );
                emit_op(
                    out,
                    "set",
                    &ident,
                    "value: int",
                    "register_int",
                    &key,
                    "value",
                );
            }
            Some(TypeDef::Counter { .. }) => {
                emit_line(out, &format!("# slot {slot:?}: counter {slot_type:?}"));
                emit_getter(
                    out,
                    &format!("get_{ident}"),
                    "Optional[int]",
                    "get_counter",
                    &key,
                );
                emit_op(out, "inc", &ident, "amount: int", "inc", &key, "amount");
                emit_op(out, "dec", &ident, "amount: int", "dec", &key, "amount");
            }
            Some(TypeDef::Text { .. }) => {
                emit_line(out, &format!("# slot {slot:?}: text {slot_type:?}"));
                emit_getter(
                    out,
                    &format!("get_{ident}"),
                    "Optional[str]",
                    "text_get",
                    &key,
                );
                emit_getter(
                    out,
                    &format!("len_{ident}"),
                    "Optional[int]",
                    "text_len",
                    &key,
                );
                emit_op(
                    out,
                    "insert",
                    &ident,
                    "index: int, text: str",
                    "text_insert",
                    &key,
                    "index, text",
                );
                emit_op(
                    out,
                    "delete",
                    &ident,
                    "index: int, count: int",
                    "text_delete",
                    &key,
                    "index, count",
                );
            }
            Some(TypeDef::List { .. }) => {
                emit_line(out, &format!("# slot {slot:?}: list {slot_type:?}"));
                emit_getter(
                    out,
                    &format!("len_{ident}"),
                    "Optional[int]",
                    "list_len",
                    &key,
                );
                out.push_str(&format!(
                    "    def get_{ident}(self, index: int) -> Optional[bytes]:\n"
                ));
                out.push_str(&format!(
                    "        return self._doc.list_get(self._path + [{key}], index)\n"
                ));
                emit_op(
                    out,
                    "insert",
                    &ident,
                    "index: int, value: bytes",
                    "list_insert",
                    &key,
                    "index, value",
                );
                emit_op(
                    out,
                    "delete",
                    &ident,
                    "index: int",
                    "list_delete",
                    &key,
                    "index",
                );
            }
            Some(TypeDef::Map { .. }) => {
                let nested = py_class_name(slot_type);
                emit_line(out, &format!("# slot {slot:?}: map {slot_type:?}"));
                out.push_str(&format!("    def {ident}(self) -> {nested:?}:\n"));
                out.push_str(&format!(
                    "        return {nested}(self._doc, self._path + [{key}])\n"
                ));
            }
            Some(TypeDef::Xml { .. }) => {
                emit_line(
                    out,
                    &format!("# slot {slot:?}: xml {slot_type:?} — accessor not yet generated"),
                );
            }
            None => {
                emit_line(
                    out,
                    &format!("# slot {slot:?}: undeclared type {slot_type:?} — skipped"),
                );
            }
        }
    }
    out.push('\n');
}

/// A read accessor: `def <accessor>(self) -> <ret>: return self._doc.<method>(path + [key])`.
fn emit_getter(out: &mut String, accessor: &str, ret: &str, method: &str, key: &str) {
    out.push_str(&format!("    def {accessor}(self) -> {ret}:\n"));
    out.push_str(&format!(
        "        return self._doc.{method}(self._path + [{key}])\n"
    ));
}

/// A write op `def <verb>_<name>(self, <sig>) -> bytes:` forwarding to
/// `self._doc.<method>(path + [key], <call_args>)`. `sig` is the Python
/// parameter list; `call_args` is how those parameters pass through to the
/// document method.
fn emit_op(
    out: &mut String,
    verb: &str,
    name: &str,
    sig: &str,
    method: &str,
    key: &str,
    call_args: &str,
) {
    out.push_str(&format!("    def {verb}_{name}(self, {sig}) -> bytes:\n"));
    out.push_str(&format!(
        "        return self._doc.{method}(self._path + [{key}], {call_args})\n"
    ));
}

/// A standalone comment line at method-body indent.
fn emit_line(out: &mut String, comment: &str) {
    out.push_str(&format!("    {comment}\n"));
}

/// The Python class name for a schema type: the type name as-is if it is already
/// a valid identifier, else sanitized. Type names are the schema's own type keys.
fn py_class_name(type_name: &str) -> String {
    py_ident(type_name)
}

/// Sanitize an arbitrary schema name into a valid Python identifier: non-`[A-Za-z0-9_]`
/// becomes `_`, and a leading digit is prefixed with `_`. Deterministic.
fn py_ident(name: &str) -> String {
    let mut ident = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            ident.push(ch);
        } else {
            ident.push('_');
        }
    }
    if ident.is_empty() {
        ident.push('_');
    }
    if ident.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        ident.insert(0, '_');
    }
    ident
}

/// A Python `bytes` literal for a slot name — the exact path key the accessor
/// addresses. Printable ASCII rides verbatim (with `"` / `\` escaped); anything
/// else is a `\xNN` escape, so an arbitrary UTF-8 slot name round-trips to its
/// bytes.
fn py_bytes_literal(name: &str) -> String {
    let mut lit = String::from("b\"");
    for &byte in name.as_bytes() {
        match byte {
            b'"' => lit.push_str("\\\""),
            b'\\' => lit.push_str("\\\\"),
            0x20..=0x7e => lit.push(byte as char),
            _ => lit.push_str(&format!("\\x{byte:02x}")),
        }
    }
    lit.push('"');
    lit
}
