//! Typed-SDK codegen: read a registered [`Schema`] and emit typed accessor
//! wrappers for a target SDK language.
//!
//! The generated code is a thin, type-annotated facade over the raw path-string
//! surface an SDK already exposes: for each declared map slot it emits an
//! accessor that forwards to the existing document methods with the slot's path
//! and type baked in, so a consumer gets `note.get_title()` instead of
//! `doc.text_get([b"title"])`. Codegen only *reads* the schema — it never alters
//! the [`Schema`] type or the wire format.
//!
//! Output is deterministic: types and slots are emitted in the schema's own
//! declaration order, and the header carries no timestamp, so regenerating an
//! unchanged schema is a no-op diff.
//!
//! Python ([`generate_python`]) and Go ([`generate_go`]) are the current targets;
//! the emitter is structured per-language so further targets follow the same shape.

use crdtsync_core::schema::{Schema, TypeDef};

/// The Go import path of the Go SDK package the generated accessors forward to.
const GO_SDK_IMPORT: &str = "github.com/faiscadev/crdtsync/sdks/go/crdtsync";

/// Emit a Python module of typed accessors for `schema`.
///
/// One class is emitted per declared map type (named after the type). Each class
/// wraps a `crdtsync.Document` plus the path prefix it lives at, and exposes a
/// typed accessor per slot that forwards to the document's path surface:
///
/// - a `register` slot → `get_<slot>() -> Optional[int]` / `set_<slot>(value)`,
/// - a `counter` slot → `get_<slot>()` / `inc_<slot>(amount)` / `dec_<slot>(amount)`,
/// - a `text` slot → `get_<slot>() -> Optional[str]` / `insert_<slot>` / `delete_<slot>` / `len_<slot>`,
/// - a `list` slot → `len_<slot>` / `get_<slot>(index)` / `insert_<slot>(index, value)` / `delete_<slot>(index)`,
/// - a `map` slot → `<slot>() -> <NestedType>`, a wrapper rooted at the nested path.
///
/// An `xml` slot (or one whose type is undeclared) is emitted as a comment: those
/// surfaces are a follow-on. A `register` is treated as an integer scalar — its
/// declared bounds are numeric; a bytes-valued register uses the raw path.
pub fn generate_python(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Generated by crdtsync-codegen from schema {:?} v{}. Do not edit.\n",
        schema.name(),
        schema.version(),
    ));
    out.push_str("# Typed accessors over crdtsync's path surface; regenerate on schema change.\n");
    out.push_str("from typing import List, Optional\n\n");

    for (type_name, def) in schema.types() {
        if let TypeDef::Map { children } = def {
            emit_python_class(&mut out, schema, type_name, children);
        }
    }

    out.push_str(&format!(
        "\ndef bind(doc) -> {:?}:\n",
        py_class_name(schema.root())
    ));
    out.push_str("    \"\"\"Wrap a crdtsync.Document at the schema root.\"\"\"\n");
    out.push_str(&format!(
        "    return {}(doc)\n",
        py_class_name(schema.root())
    ));
    out
}

/// Emit one Python wrapper class for a map type and its slots.
fn emit_python_class(
    out: &mut String,
    schema: &Schema,
    type_name: &str,
    children: &[(String, String)],
) {
    let class = py_class_name(type_name);
    out.push_str(&format!("class {class}:\n"));
    out.push_str(&format!(
        "    \"\"\"Typed accessors for schema type {type_name:?}.\"\"\"\n\n"
    ));
    out.push_str("    def __init__(self, doc, path: Optional[List[bytes]] = None) -> None:\n");
    out.push_str("        self._doc = doc\n");
    out.push_str("        self._path = list(path) if path else []\n");

    for (slot, slot_type) in children {
        out.push('\n');
        let key = py_bytes_literal(slot);
        let ident = py_ident(slot);
        match schema.type_def(slot_type) {
            Some(TypeDef::Register { .. }) => {
                emit_line(out, &format!("# slot {slot:?}: register {slot_type:?}"));
                emit_getter(
                    out,
                    &format!("get_{ident}"),
                    "Optional[int]",
                    "get_int",
                    &key,
                );
                emit_op(
                    out,
                    "set",
                    &ident,
                    "value: int",
                    "register_int",
                    &key,
                    "value",
                );
            }
            Some(TypeDef::Counter { .. }) => {
                emit_line(out, &format!("# slot {slot:?}: counter {slot_type:?}"));
                emit_getter(
                    out,
                    &format!("get_{ident}"),
                    "Optional[int]",
                    "get_counter",
                    &key,
                );
                emit_op(out, "inc", &ident, "amount: int", "inc", &key, "amount");
                emit_op(out, "dec", &ident, "amount: int", "dec", &key, "amount");
            }
            Some(TypeDef::Text { .. }) => {
                emit_line(out, &format!("# slot {slot:?}: text {slot_type:?}"));
                emit_getter(
                    out,
                    &format!("get_{ident}"),
                    "Optional[str]",
                    "text_get",
                    &key,
                );
                emit_getter(
                    out,
                    &format!("len_{ident}"),
                    "Optional[int]",
                    "text_len",
                    &key,
                );
                emit_op(
                    out,
                    "insert",
                    &ident,
                    "index: int, text: str",
                    "text_insert",
                    &key,
                    "index, text",
                );
                emit_op(
                    out,
                    "delete",
                    &ident,
                    "index: int, count: int",
                    "text_delete",
                    &key,
                    "index, count",
                );
            }
            Some(TypeDef::List { .. }) => {
                emit_line(out, &format!("# slot {slot:?}: list {slot_type:?}"));
                emit_getter(
                    out,
                    &format!("len_{ident}"),
                    "Optional[int]",
                    "list_len",
                    &key,
                );
                out.push_str(&format!(
                    "    def get_{ident}(self, index: int) -> Optional[bytes]:\n"
                ));
                out.push_str(&format!(
                    "        return self._doc.list_get(self._path + [{key}], index)\n"
                ));
                emit_op(
                    out,
                    "insert",
                    &ident,
                    "index: int, value: bytes",
                    "list_insert",
                    &key,
                    "index, value",
                );
                emit_op(
                    out,
                    "delete",
                    &ident,
                    "index: int",
                    "list_delete",
                    &key,
                    "index",
                );
            }
            Some(TypeDef::Map { .. }) => {
                let nested = py_class_name(slot_type);
                emit_line(out, &format!("# slot {slot:?}: map {slot_type:?}"));
                out.push_str(&format!("    def {ident}(self) -> {nested:?}:\n"));
                out.push_str(&format!(
                    "        return {nested}(self._doc, self._path + [{key}])\n"
                ));
            }
            Some(TypeDef::Xml { .. }) => {
                emit_line(
                    out,
                    &format!("# slot {slot:?}: xml {slot_type:?} — accessor not yet generated"),
                );
            }
            None => {
                emit_line(
                    out,
                    &format!("# slot {slot:?}: undeclared type {slot_type:?} — skipped"),
                );
            }
        }
    }
    out.push('\n');
}

/// A read accessor: `def <accessor>(self) -> <ret>: return self._doc.<method>(path + [key])`.
fn emit_getter(out: &mut String, accessor: &str, ret: &str, method: &str, key: &str) {
    out.push_str(&format!("    def {accessor}(self) -> {ret}:\n"));
    out.push_str(&format!(
        "        return self._doc.{method}(self._path + [{key}])\n"
    ));
}

/// A write op `def <verb>_<name>(self, <sig>) -> bytes:` forwarding to
/// `self._doc.<method>(path + [key], <call_args>)`. `sig` is the Python
/// parameter list; `call_args` is how those parameters pass through to the
/// document method.
fn emit_op(
    out: &mut String,
    verb: &str,
    name: &str,
    sig: &str,
    method: &str,
    key: &str,
    call_args: &str,
) {
    out.push_str(&format!("    def {verb}_{name}(self, {sig}) -> bytes:\n"));
    out.push_str(&format!(
        "        return self._doc.{method}(self._path + [{key}], {call_args})\n"
    ));
}

/// A standalone comment line at method-body indent.
fn emit_line(out: &mut String, comment: &str) {
    out.push_str(&format!("    {comment}\n"));
}

/// The Python class name for a schema type: the type name as-is if it is already
/// a valid identifier, else sanitized. Type names are the schema's own type keys.
fn py_class_name(type_name: &str) -> String {
    py_ident(type_name)
}

/// Sanitize an arbitrary schema name into a valid Python identifier: non-`[A-Za-z0-9_]`
/// becomes `_`, and a leading digit is prefixed with `_`. Deterministic.
fn py_ident(name: &str) -> String {
    let mut ident = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            ident.push(ch);
        } else {
            ident.push('_');
        }
    }
    if ident.is_empty() {
        ident.push('_');
    }
    if ident.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        ident.insert(0, '_');
    }
    ident
}

/// A Python `bytes` literal for a slot name — the exact path key the accessor
/// addresses. Printable ASCII rides verbatim (with `"` / `\` escaped); anything
/// else is a `\xNN` escape, so an arbitrary UTF-8 slot name round-trips to its
/// bytes.
fn py_bytes_literal(name: &str) -> String {
    let mut lit = String::from("b\"");
    for &byte in name.as_bytes() {
        match byte {
            b'"' => lit.push_str("\\\""),
            b'\\' => lit.push_str("\\\\"),
            0x20..=0x7e => lit.push(byte as char),
            _ => lit.push_str(&format!("\\x{byte:02x}")),
        }
    }
    lit.push('"');
    lit
}

/// Emit a Go package of typed accessors for `schema`, under package name `package`.
///
/// One struct is emitted per declared map type (named after the type). Each struct
/// holds a `*crdtsync.Document` plus the path prefix it lives at, and exposes a
/// typed method per slot that forwards to the SDK's path surface, mirroring
/// [`generate_python`]:
///
/// - a `register` slot → `Get<Slot>() (int64, bool)` / `Set<Slot>(value int64) []byte`,
/// - a `counter` slot → `Get<Slot>() (int64, bool)` / `Inc<Slot>` / `Dec<Slot>`,
/// - a `text` slot → `Get<Slot>() (string, bool)` / `Len<Slot>` / `Insert<Slot>` / `Delete<Slot>`,
/// - a `list` slot → `Len<Slot>` / `Get<Slot>(index uint)` / `Insert<Slot>` / `Delete<Slot>`,
/// - a `map` slot → `<Slot>() *<NestedType>`, a wrapper rooted at the nested path.
///
/// An `xml` slot (or one whose type is undeclared) is emitted as a comment: those
/// surfaces are a follow-on. Getters forward the underlying `(value, ok)` pair as-is.
/// Output is deterministic: types and slots ride the schema's declaration order and
/// the header carries no timestamp, so regenerating an unchanged schema is a no-op diff.
pub fn generate_go(schema: &Schema, package: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "// Code generated by crdtsync-codegen from schema {:?} v{}. DO NOT EDIT.\n",
        schema.name(),
        schema.version(),
    ));
    out.push_str("// Typed accessors over crdtsync's path surface; regenerate on schema change.\n");
    out.push_str(&format!("package {}\n\n", go_ident(package)));
    out.push_str(&format!("import \"{GO_SDK_IMPORT}\"\n"));

    for (type_name, def) in schema.types() {
        if let TypeDef::Map { children } = def {
            emit_go_struct(&mut out, schema, type_name, children);
        }
    }

    let root = go_type_name(schema.root());
    out.push('\n');
    out.push_str("// Bind wraps a crdtsync.Document at the schema root.\n");
    out.push_str(&format!(
        "func Bind(doc *crdtsync.Document) *{root} {{\n\treturn &{root}{{doc: doc}}\n}}\n"
    ));

    // joinPath copies the prefix so sibling and nested accessors never alias one
    // backing array — appending in place would corrupt a shared path slice.
    out.push('\n');
    out.push_str("// joinPath returns prefix with key appended, copying so sibling accessors\n");
    out.push_str("// never share a backing array.\n");
    out.push_str("func joinPath(prefix [][]byte, key []byte) [][]byte {\n");
    out.push_str("\tout := make([][]byte, len(prefix)+1)\n");
    out.push_str("\tcopy(out, prefix)\n");
    out.push_str("\tout[len(prefix)] = key\n");
    out.push_str("\treturn out\n");
    out.push_str("}\n");
    out
}

/// Emit one Go wrapper struct for a map type and its slots.
fn emit_go_struct(
    out: &mut String,
    schema: &Schema,
    type_name: &str,
    children: &[(String, String)],
) {
    let ty = go_type_name(type_name);
    out.push('\n');
    out.push_str(&format!(
        "// {ty} holds typed accessors for schema type {type_name:?}.\n"
    ));
    out.push_str(&format!("type {ty} struct {{\n"));
    out.push_str("\tdoc  *crdtsync.Document\n");
    out.push_str("\tpath [][]byte\n");
    out.push_str("}\n");

    for (slot, slot_type) in children {
        out.push('\n');
        let key = go_bytes_literal(slot);
        let name = go_ident_exported(slot);
        match schema.type_def(slot_type) {
            Some(TypeDef::Register { .. }) => {
                emit_go_comment(out, &format!("slot {slot:?}: register {slot_type:?}"));
                emit_go_getter(
                    out,
                    &ty,
                    &format!("Get{name}"),
                    "(int64, bool)",
                    "GetInt",
                    &key,
                );
                emit_go_op(
                    out,
                    &ty,
                    &format!("Set{name}"),
                    "value int64",
                    "RegisterInt",
                    &key,
                    "value",
                );
            }
            Some(TypeDef::Counter { .. }) => {
                emit_go_comment(out, &format!("slot {slot:?}: counter {slot_type:?}"));
                emit_go_getter(
                    out,
                    &ty,
                    &format!("Get{name}"),
                    "(int64, bool)",
                    "GetCounter",
                    &key,
                );
                emit_go_op(
                    out,
                    &ty,
                    &format!("Inc{name}"),
                    "amount uint32",
                    "Inc",
                    &key,
                    "amount",
                );
                emit_go_op(
                    out,
                    &ty,
                    &format!("Dec{name}"),
                    "amount uint32",
                    "Dec",
                    &key,
                    "amount",
                );
            }
            Some(TypeDef::Text { .. }) => {
                emit_go_comment(out, &format!("slot {slot:?}: text {slot_type:?}"));
                emit_go_getter(
                    out,
                    &ty,
                    &format!("Get{name}"),
                    "(string, bool)",
                    "TextGet",
                    &key,
                );
                emit_go_getter(
                    out,
                    &ty,
                    &format!("Len{name}"),
                    "(uint, bool)",
                    "TextLen",
                    &key,
                );
                emit_go_op(
                    out,
                    &ty,
                    &format!("Insert{name}"),
                    "index uint, text string",
                    "TextInsert",
                    &key,
                    "index, text",
                );
                emit_go_op(
                    out,
                    &ty,
                    &format!("Delete{name}"),
                    "index, count uint",
                    "TextDelete",
                    &key,
                    "index, count",
                );
            }
            Some(TypeDef::List { .. }) => {
                emit_go_comment(out, &format!("slot {slot:?}: list {slot_type:?}"));
                emit_go_getter(
                    out,
                    &ty,
                    &format!("Len{name}"),
                    "(uint, bool)",
                    "ListLen",
                    &key,
                );
                out.push_str(&format!(
                    "func (x *{ty}) Get{name}(index uint) ([]byte, bool) {{\n"
                ));
                out.push_str(&format!(
                    "\treturn x.doc.ListGet(joinPath(x.path, {key}), index)\n}}\n"
                ));
                emit_go_op(
                    out,
                    &ty,
                    &format!("Insert{name}"),
                    "index uint, value []byte",
                    "ListInsert",
                    &key,
                    "index, value",
                );
                emit_go_op(
                    out,
                    &ty,
                    &format!("Delete{name}"),
                    "index uint",
                    "ListDelete",
                    &key,
                    "index",
                );
            }
            Some(TypeDef::Map { .. }) => {
                let nested = go_type_name(slot_type);
                emit_go_comment(out, &format!("slot {slot:?}: map {slot_type:?}"));
                out.push_str(&format!("func (x *{ty}) {name}() *{nested} {{\n"));
                out.push_str(&format!(
                    "\treturn &{nested}{{doc: x.doc, path: joinPath(x.path, {key})}}\n}}\n"
                ));
            }
            Some(TypeDef::Xml { .. }) => {
                emit_go_comment(
                    out,
                    &format!("slot {slot:?}: xml {slot_type:?} — accessor not yet generated"),
                );
            }
            None => {
                emit_go_comment(
                    out,
                    &format!("slot {slot:?}: undeclared type {slot_type:?} — skipped"),
                );
            }
        }
    }
}

/// A read method: `func (x *Ty) Name() ret { return x.doc.Method(joinPath(x.path, key)) }`.
fn emit_go_getter(out: &mut String, ty: &str, name: &str, ret: &str, method: &str, key: &str) {
    out.push_str(&format!("func (x *{ty}) {name}() {ret} {{\n"));
    out.push_str(&format!(
        "\treturn x.doc.{method}(joinPath(x.path, {key}))\n}}\n"
    ));
}

/// A write op returning the encoded ops (`[]byte`), forwarding `call_args` through
/// to the document method after the path.
fn emit_go_op(
    out: &mut String,
    ty: &str,
    name: &str,
    sig: &str,
    method: &str,
    key: &str,
    call_args: &str,
) {
    out.push_str(&format!("func (x *{ty}) {name}({sig}) []byte {{\n"));
    out.push_str(&format!(
        "\treturn x.doc.{method}(joinPath(x.path, {key}), {call_args})\n}}\n"
    ));
}

/// A standalone `// ` comment line at package indent.
fn emit_go_comment(out: &mut String, comment: &str) {
    out.push_str(&format!("// {comment}\n"));
}

/// The Go struct type name for a schema type: an exported (upper-first) identifier.
fn go_type_name(type_name: &str) -> String {
    go_ident_exported(type_name)
}

/// Sanitize a schema name into a valid Go identifier: non-`[A-Za-z0-9_]` becomes
/// `_`, and a name not starting with a letter or `_` is prefixed with `_`.
fn go_ident(name: &str) -> String {
    let mut ident = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            ident.push(ch);
        } else {
            ident.push('_');
        }
    }
    if ident.is_empty() {
        ident.push('_');
    }
    if !ident
        .chars()
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
    {
        ident.insert(0, '_');
    }
    ident
}

/// An exported Go identifier for a schema name: sanitized, forced to start with an
/// upper-case ASCII letter (a leading digit or unusable first char gains an `X`
/// prefix), so a method or type name is always valid and exported. Deterministic.
fn go_ident_exported(name: &str) -> String {
    let mut ident = go_ident(name);
    let first = ident.chars().next().unwrap_or('_');
    if !first.is_ascii_alphabetic() {
        ident.insert(0, 'X');
    }
    let mut chars = ident.chars();
    let head = chars.next().unwrap().to_ascii_uppercase();
    let mut exported = String::with_capacity(ident.len());
    exported.push(head);
    exported.push_str(chars.as_str());
    exported
}

/// A Go `[]byte("…")` literal for a slot name — the exact path key the accessor
/// addresses. Printable ASCII rides verbatim (with `"` / `\` escaped); anything
/// else is a `\xNN` escape, so an arbitrary UTF-8 slot name round-trips to its bytes.
fn go_bytes_literal(name: &str) -> String {
    let mut lit = String::from("[]byte(\"");
    for &byte in name.as_bytes() {
        match byte {
            b'"' => lit.push_str("\\\""),
            b'\\' => lit.push_str("\\\\"),
            0x20..=0x7e => lit.push(byte as char),
            _ => lit.push_str(&format!("\\x{byte:02x}")),
        }
    }
    lit.push_str("\")");
    lit
}
