//! Go codegen: the emitted source is deterministic and matches the committed
//! golden (so a regenerate is a no-op diff), and forwards each slot to the right
//! path-surface method. The golden lives in the Go SDK tree so `go test` compiles
//! and round-trips it (sdks/go/notegen); here it is pinned byte-for-byte.

use crdtsync_codegen::generate_go;
use crdtsync_core::schema::Schema;

const SCHEMA_SRC: &str = include_str!("fixtures/note.schema.json");
const GOLDEN: &str = include_str!("../../../sdks/go/notegen/note_generated.go");
const PACKAGE: &str = "notegen";

fn schema() -> Schema {
    Schema::parse(SCHEMA_SRC).expect("fixture schema parses")
}

#[test]
fn generation_is_deterministic() {
    // Re-parse the source into a fresh Schema each time, so this catches any
    // nondeterminism that could leak from the parse (e.g. hash-ordered state),
    // not just a same-instance tautology.
    let a = generate_go(&Schema::parse(SCHEMA_SRC).unwrap(), PACKAGE);
    let b = generate_go(&Schema::parse(SCHEMA_SRC).unwrap(), PACKAGE);
    assert_eq!(a, b);
}

#[test]
fn output_matches_the_committed_golden() {
    // If this fails, regenerate:
    //   cargo run -p crdtsync-codegen -- crates/codegen/tests/fixtures/note.schema.json \
    //     --lang go --package notegen -o sdks/go/notegen/note_generated.go
    assert_eq!(generate_go(&schema(), PACKAGE), GOLDEN);
}

#[test]
fn header_carries_the_schema_name_and_version_but_no_timestamp() {
    let out = generate_go(&schema(), PACKAGE);
    assert!(out.starts_with("// Code generated by crdtsync-codegen from schema \"note\" v1."));
    assert!(out.contains("\npackage notegen\n"));
    assert!(out.contains("import \"github.com/faiscadev/crdtsync/sdks/go/crdtsync\""));
}

#[test]
fn each_slot_forwards_to_its_typed_path_method() {
    let out = generate_go(&schema(), PACKAGE);
    // text slot -> TextGet / TextInsert at the slot's path key
    assert!(out.contains("return x.doc.TextGet(joinPath(x.path, []byte(\"title\")))"));
    assert!(
        out.contains("return x.doc.TextInsert(joinPath(x.path, []byte(\"title\")), index, text)")
    );
    // counter slot -> GetCounter / Inc / Dec
    assert!(out.contains("return x.doc.GetCounter(joinPath(x.path, []byte(\"views\")))"));
    assert!(out.contains("return x.doc.Inc(joinPath(x.path, []byte(\"views\")), amount)"));
    // list slot -> ListLen / ListGet
    assert!(out.contains("return x.doc.ListGet(joinPath(x.path, []byte(\"tags\")), index)"));
    // nested map slot -> a wrapper rooted at the extended path
    assert!(out.contains("return &Meta{doc: x.doc, path: joinPath(x.path, []byte(\"meta\"))}"));
    // register slot inside the nested map -> GetInt / RegisterInt
    assert!(out.contains("return x.doc.RegisterInt(joinPath(x.path, []byte(\"priority\")), value)"));
    // the root Bind() convenience
    assert!(out.contains("func Bind(doc *crdtsync.Document) *Note {"));
}

#[test]
fn an_unusual_slot_name_becomes_a_safe_exported_identifier_and_byte_key() {
    // A hyphenated slot name is not a Go identifier: the method suffix is
    // sanitized and exported while the path key keeps the exact bytes.
    let src = r#"{
        "schema": "s", "version": 1, "root": "R",
        "types": {
            "R": { "kind": "map", "children": { "a-b": "C" } },
            "C": { "kind": "counter" }
        }
    }"#;
    let out = generate_go(&Schema::parse(src).unwrap(), "gen");
    assert!(out.contains("func (x *R) GetA_b() (int64, bool)"));
    assert!(out.contains("joinPath(x.path, []byte(\"a-b\"))"));
}
