//! Python codegen: the emitted source is deterministic and matches the committed
//! golden (so a regenerate is a no-op diff), and forwards each slot to the right
//! path-surface method.

use crdtsync_codegen::generate_python;
use crdtsync_core::schema::Schema;

const SCHEMA_SRC: &str = include_str!("fixtures/note.schema.json");
const GOLDEN: &str = include_str!("fixtures/note_generated.py");

fn schema() -> Schema {
    Schema::parse(SCHEMA_SRC).expect("fixture schema parses")
}

#[test]
fn generation_is_deterministic() {
    // Re-parse the source into a fresh Schema each time, so this catches any
    // nondeterminism that could leak from the parse (e.g. hash-ordered state),
    // not just a same-instance tautology.
    let a = generate_python(&Schema::parse(SCHEMA_SRC).unwrap());
    let b = generate_python(&Schema::parse(SCHEMA_SRC).unwrap());
    assert_eq!(a, b);
}

#[test]
fn output_matches_the_committed_golden() {
    // If this fails, regenerate:
    //   cargo run -p crdtsync-codegen -- crates/codegen/tests/fixtures/note.schema.json \
    //     -o crates/codegen/tests/fixtures/note_generated.py
    assert_eq!(generate_python(&schema()), GOLDEN);
}

#[test]
fn header_carries_the_schema_name_and_version_but_no_timestamp() {
    let out = generate_python(&schema());
    assert!(out.starts_with("# Generated by crdtsync-codegen from schema \"note\" v1."));
}

#[test]
fn each_slot_forwards_to_its_typed_path_method() {
    let out = generate_python(&schema());
    // text slot -> text_get / text_insert at the slot's path key
    assert!(out.contains("return self._doc.text_get(self._path + [b\"title\"])"));
    assert!(out.contains("return self._doc.text_insert(self._path + [b\"title\"], index, text)"));
    // counter slot -> get_counter / inc / dec
    assert!(out.contains("return self._doc.get_counter(self._path + [b\"views\"])"));
    assert!(out.contains("return self._doc.inc(self._path + [b\"views\"], amount)"));
    // list slot -> list_len / list_get
    assert!(out.contains("return self._doc.list_get(self._path + [b\"tags\"], index)"));
    // nested map slot -> a wrapper rooted at the extended path
    assert!(out.contains("return Meta(self._doc, self._path + [b\"meta\"])"));
    // register slot inside the nested map -> get_int / register_int
    assert!(out.contains("return self._doc.register_int(self._path + [b\"priority\"], value)"));
    // the root bind() convenience
    assert!(out.contains("def bind(doc) -> \"Note\":"));
}

#[test]
fn an_unusual_slot_name_becomes_a_safe_identifier_and_byte_key() {
    // A hyphenated slot name is not a Python identifier: the method suffix is
    // sanitized while the path key keeps the exact bytes.
    let src = r#"{
        "schema": "s", "version": 1, "root": "R",
        "types": {
            "R": { "kind": "map", "children": { "a-b": "C" } },
            "C": { "kind": "counter" }
        }
    }"#;
    let out = generate_python(&Schema::parse(src).unwrap());
    assert!(out.contains("def get_a_b(self)"));
    assert!(out.contains("self._path + [b\"a-b\"]"));
}
