// Code generated by crdtsync-codegen from schema "collide" v1. DO NOT EDIT.
// Typed accessors over crdtsync's path surface; regenerate on schema change.
package collidegen

import "github.com/faiscadev/crdtsync/sdks/go/crdtsync"

// C holds typed accessors for schema type "C".
type C struct {
	doc  *crdtsync.Document
	path [][]byte
}

// slot "a-b": counter "Ctr"
func (x *C) GetA_b() (int64, bool) {
	return x.doc.GetCounter(joinPath(x.path, []byte("a-b")))
}
func (x *C) IncA_b(amount uint32) []byte {
	return x.doc.Inc(joinPath(x.path, []byte("a-b")), amount)
}
func (x *C) DecA_b(amount uint32) []byte {
	return x.doc.Dec(joinPath(x.path, []byte("a-b")), amount)
}

// slot "a_b": counter "Ctr"
func (x *C) GetA_b_2() (int64, bool) {
	return x.doc.GetCounter(joinPath(x.path, []byte("a_b")))
}
func (x *C) IncA_b_2(amount uint32) []byte {
	return x.doc.Inc(joinPath(x.path, []byte("a_b")), amount)
}
func (x *C) DecA_b_2(amount uint32) []byte {
	return x.doc.Dec(joinPath(x.path, []byte("a_b")), amount)
}

// slot "a b": counter "Ctr"
func (x *C) GetA_b_3() (int64, bool) {
	return x.doc.GetCounter(joinPath(x.path, []byte("a b")))
}
func (x *C) IncA_b_3(amount uint32) []byte {
	return x.doc.Inc(joinPath(x.path, []byte("a b")), amount)
}
func (x *C) DecA_b_3(amount uint32) []byte {
	return x.doc.Dec(joinPath(x.path, []byte("a b")), amount)
}

// Bind wraps a crdtsync.Document at the schema root.
func Bind(doc *crdtsync.Document) *C {
	return &C{doc: doc}
}

// joinPath returns prefix with key appended, copying so sibling accessors
// never share a backing array.
func joinPath(prefix [][]byte, key []byte) [][]byte {
	out := make([][]byte, len(prefix)+1)
	copy(out, prefix)
	out[len(prefix)] = key
	return out
}
